### ISSUE TITLE
How could we make the selecting a variable category modal cleaner?

### ISSUE THREAD

**Issue by DominicSherman** [DominicSherman/easy-budget-mobile#49]
When you select a variable category, we show you the information about spent vs budgeted vs remaining, as well as a single list view of all the expenses for that category. We also allow you to edit the name/values of the category, or delete it. I think all of this is necessary, but it is a lot going on in one screen and kind of jumbles it together. How could we make it look better/more clear cut?

**Comment by msherman93** [comment]
So I got some feedback from Gregory on this screen actually. 

![FullSizeRender](https://user-images.githubusercontent.com/43038199/75183960-2c6ec300-5709-11ea-9bd3-59f9f37d7d6f.jpeg)
Move the + sign to the bottom right so that as variable categories pile up it won't get in the way. Also switch the direction of the drop down arrows so that the unselected arrow points down (indicating drop down) and the selected arrow points up (indicating recollapse)
